//    LOADING
export const START_LOADING = "START_LOADING";
export const STOP_LOADING = "STOP_LOADING";

//    MOVIES
export const GET_POPULAR_MOVIES = "GET_POPULAR_MOVIES";
export const GET_ALL_GENRES = "GET_ALL_GENRES";
export const SEARCH_MOVIES = "SEARCH_MOVIES";
export const CLEAR_SEARCH_RESULT = "CLEAR_SEARCH_RESULT";
export const GET_UPCOMING = "GET_UPCOMING";
export const OPEN_MOVIE_DETAILS = "OPEN_MOVIE_DETAILS";
export const CLOSE_MOVIE_DETAILS = "CLOSE_MOVIE_DETAILS";
export const GET_MOVIE_COLLECTION = "GET_MOVIE_COLLECTION";
export const GET_RECOMMENDATIONS = "GET_RECOMMENDATIONS";
export const GET_MOVIE_CREDITS = "GET_MOVIE_CREDITS";